name: shadcnui_starter_app
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  shadcn_ui: ^0.8.1
  provider: ^6.0.0
  shared_preferences: ^2.3.2
  google_fonts: ^6.2.1
  go_router: ^14.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
